language: java
sudo: required
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
before_install:
  - chmod +x mvnw

script: "mvn test"

after_success:
  - bash <(curl -s https://codecov.io/bash)